### ISSUE TITLE
add splash screen

### ISSUE THREAD

**Issue by rudrankbasant** [IEEE-VIT/Coint#7]

**Comment by V9vek** [comment]
Hi @rudrankbasant @ananya190 I would like to work on this, please assign it to me
Before that I want to clarify like, which icon or image or text you want in the Splash Screen? if there is any specific design, you can share some image link or something

**Comment by rudrankbasant** [comment]
Hey @V9vek, I'll suggest you can wait for the app icon to be submitted before we make a splash screen. Then you can use the image for it. Until then you can work on the other issue you've been assigned.

**Comment by V9vek** [comment]
Sure

**Comment by rudrankbasant** [comment]
Hey @V9vek are you still working on this issue?

**Comment by V9vek** [comment]
If app icon is ready and added, I will do the splash screen by tomorrow morning only
I didn't check that icon was added.

**Comment by rudrankbasant** [comment]
No problem @V9vek!

**Comment by V9vek** [comment]
@rudrankbasant i am getting errors which I can not resolve right now. So you can unassign me for this issue.

**Comment by trunX04** [comment]
@rudrankbasant can i work on this?
