### ISSUE TITLE
create item view layout for value list

### ISSUE THREAD

**Issue by rudrankbasant** [IEEE-VIT/Coint#8]
make an item view layout with the following details:

On the left:
1) coin's icon
2) coin's  abbreviation
3) coin's full name below abbreviation (with text size smaller than the abbreviation).

On the right:
1) the current value of the coin

**Comment by V9vek** [comment]
Hi @rudrankbasant @ananya190 I would like to work on this, if this is open for contribution, please assign it to me

**Comment by V9vek** [comment]
I have opened the PR for the same, please check it
